# Generated by Django 5.1.6 on 2025-02-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationfield',
            name='is_higher_better',
            field=models.BooleanField(default=False, help_text='Определяет выделение лучшего значения в сравнениях', verbose_name='Чем выше тем лучше'),
        ),
    ]
