# Generated by Django 5.1.6 on 2025-03-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_specificationfield_is_higher_better'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
