# Generated by Django 5.1.6 on 2025-02-11 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='devices/', verbose_name='Изображение')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория устройств',
                'verbose_name_plural': 'Категории устройств',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('is_higher_better', models.BooleanField(default=True, verbose_name='Чем больше, тем лучше')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное сравнение')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('devices', models.ManyToManyField(to='comparisons.device', verbose_name='Устройства')),
            ],
            options={
                'verbose_name': 'Сравнение',
                'verbose_name_plural': 'Сравнения',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisons.devicecategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ComparisonVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comparisons.comparison', verbose_name='Сравнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisons.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Голос в сравнении',
                'verbose_name_plural': 'Голоса в сравнении',
                'unique_together': {('comparison', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DeviceSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='comparisons.device', verbose_name='Устройство')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisons.specification', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика устройства',
                'verbose_name_plural': 'Характеристики устройства',
                'unique_together': {('device', 'specification')},
            },
        ),
    ]
