# Generated by Django 5.1.6 on 2025-02-12 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория характеристик',
                'verbose_name_plural': 'Категории характеристик',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='devicespecification',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение'),
        ),
        migrations.CreateModel(
            name='SpecificationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Объяснение характеристики', verbose_name='Описание')),
                ('unit', models.CharField(blank=True, help_text='Например: мм, кг, МГц', max_length=20, verbose_name='Единица измерения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='comparisons.specificationcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Поле характеристики',
                'verbose_name_plural': 'Поля характеристик',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='devicespecification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devicespecification',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comparisons.specificationfield', verbose_name='Характеристика'),
        ),
        migrations.AlterUniqueTogether(
            name='devicespecification',
            unique_together={('device', 'field')},
        ),
        migrations.RemoveField(
            model_name='devicespecification',
            name='specification',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
