# Generated by Django 5.1.6 on 2025-02-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0002_specificationcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comparisons.devicecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
