# Generated by Django 5.1.6 on 2025-03-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_reaction_delete_commentvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
