# Generated by Django 5.1.6 on 2025-02-17 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '__first__'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='achievements/', verbose_name='Иконка')),
                ('condition_value', models.PositiveIntegerField(verbose_name='Значение для получения')),
                ('condition_type', models.CharField(choices=[('articles_read', 'Прочитано статей'), ('comments_count', 'Написано комментариев'), ('comparisons_created', 'Создано сравнений'), ('votes_count', 'Сделано голосов')], max_length=50, verbose_name='Тип достижения')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='Аватар')),
                ('articles_read', models.PositiveIntegerField(default=0, verbose_name='Прочитано статей')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Количество комментариев')),
                ('comparisons_created', models.PositiveIntegerField(default=0, verbose_name='Создано сравнений')),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Количество голосов')),
                ('notify_on_comment_reply', models.BooleanField(default=True, verbose_name='Уведомлять об ответах на комментарии')),
                ('notify_on_article_update', models.BooleanField(default=True, verbose_name='Уведомлять об обновлениях избранных статей')),
                ('notify_on_device_update', models.BooleanField(default=True, verbose_name='Уведомлять об обновлениях избранных устройств')),
                ('favorite_articles', models.ManyToManyField(blank=True, related_name='favorited_by', to='articles.article', verbose_name='Избранные статьи')),
                ('favorite_devices', models.ManyToManyField(blank=True, related_name='favorited_by', to='devices.device', verbose_name='Избранные устройства')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
